import {solar as calculateSolar} from './solar.js';
import {parks, activePark} from './parks.js';
import {parkDate,homeGames,nextHomeGame,gameLocal} from './schedule.js';
let park=activePark;
const solar=(date,minutes)=>{const result=calculateSolar(date,minutes,park),a=park.bearing*Math.PI/180,[x,y,z]=result.dir;return {...result,dir:[x*Math.cos(a)-z*Math.sin(a),y,x*Math.sin(a)+z*Math.cos(a)]}};
const $=id=>document.getElementById(id),canvas=$('park'),ctx=canvas.getContext('2d');
const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,s)=>a.map(v=>v*s),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const sections=[],faces=[],blockers=[],labels=[];let yaw=0,pitch=.95,zoom=1,W=0,H=0,selection=102,minute=790,date=seasonDate(),sun,dirty=true,playing=false,last=0,hitPolys=[];
function seasonDate(){const d=parkDate(new Date(),park.timeZone);return d<'2026-01-01'?'2026-01-01':d>'2026-12-31'?'2026-12-31':d}
let focusPoint=[0,8,40],cameraTween=null,hovered=null,mode='home';
const palettes={petco:['#4b7e7c','#5f9390','#82a5a0'],dodger:['#d8bc77','#b8c995','#77afbe','#94b5d0'],oracle:['#527f71','#698d7f','#8ca99b']};
const polar=(r,t,y)=>[r*Math.sin(t),y,40+r*Math.cos(t)];
function face(points,color,kind='structure',sec=null){const f={points,color,kind,sec};faces.push(f);return f}
function blocker(points,name){const e1=sub(points[1],points[0]),e2=sub(points[2],points[0]);blockers.push({p:points[0],e1,e2,name});if(points.length===4)blockers.push({p:points[0],e1:sub(points[2],points[0]),e2:sub(points[3],points[0]),name})}
function panel(points,color,name,kind='structure'){face(points,color,kind);blocker(points,name)}
function box(x,z,w,d,h,color,name){const p=[[x,0,z],[x+w,0,z],[x+w,0,z+d],[x,0,z+d]],top=p.map(v=>[v[0],h,v[2]]);panel(top,color,name);for(let i=0;i<4;i++)panel([p[i],p[(i+1)%4],top[(i+1)%4],top[i]],color,name)}
function buildPark(){
sections.length=faces.length=blockers.length=labels.length=0;
for(let tier=0;tier<park.levels.length;tier++){const level=park.levels[tier];for(let i=level.from??0;i<=(level.to??23);i++){
const start=(45+i*11.25)*Math.PI/180+.012,end=(45+(i+1)*11.25)*Math.PI/180-.012,r0=level.r,height=level.h,depth=level.d;
const id=level.base+(i<12?23-i*2:2+(i-12)*2),s={id,start,end,r0,height,depth,tier,index:i,name:level.name};sections.push(s);s.position=polar(r0+depth*.52,(start+end)/2,height+depth*.24+2);labels.push(s);
for(let row=1;row<=20;row++){const ri=r0+(row-1)*depth/20,ro=r0+row*depth/20,y=height+row*depth/20*.47;face([polar(ri,start,y),polar(ro,start,y),polar(ro,end,y),polar(ri,end,y)],'#a2adb0','row',id);
for(let k=0;k<4;k++){const a=start+(end-start)*k/4,b=start+(end-start)*(k+1)/4;face([polar(ri,a,y+.05),polar(ro,a,y+.05),polar(ro,b,y+.05),polar(ri,b,y+.05)],'#e5b852','seats',id).sample={row,seat:k*5+3}}}
const back=height+depth*.47;const concourse=face([polar(r0+depth,start,back+.1),polar(r0+depth+2.5,start,back+.1),polar(r0+depth+2.5,end,back+.1),polar(r0+depth,end,back+.1)],'#dce1d9','concourse');concourse.samplePoint=polar(r0+depth+1.2,(start+end)/2,back+.5);panel([polar(r0,start,height-.5),polar(r0+depth,start,back-.5),polar(r0+depth,end,back-.5),polar(r0,end,height-.5)],tier===0?'#b4c0c4':'#c8d0d2',`${level.name} deck`);
panel([polar(r0+depth,start,0),polar(r0+depth,end,0),polar(r0+depth,end,back),polar(r0+depth,start,back)],'#b5c4ca',`${level.name} rear wall`);
const roof=park.canopy;if(tier===park.levels.length-1&&roof&&i>=roof.from&&i<=roof.to)panel([polar(roof.inner,start,roof.h),polar(roof.outer,start,roof.h+2),polar(roof.outer,end,roof.h+2),polar(roof.inner,end,roof.h)],'#d7dfe1','Upper canopy','roof');
}}
const outfield=park.field.map((feet,i)=>{const a=(-45+i*22.5)*Math.PI/180;return [feet*.3048*Math.sin(a),.1,feet*.3048*Math.cos(a)]});
face([[0,.1,0],...outfield],'#6da37d','field');
face([[0,.2,-5],[24,.2,20],[0,.2,45],[-24,.2,20]],'#cda880','field');face([[0,.3,3],[17,.3,20],[0,.3,37],[-17,.3,20]],'#7ca889','field');
for(const [x,z] of [[19.4,19.4],[0,38.8],[-19.4,19.4]])face([[x-1,.5,z],[x,.5,z+1],[x+1,.5,z],[x,.5,z-1]],'#ffffff','field');
face([[-1.1,.6,1.1],[1.1,.6,1.1],[1.1,.6,0],[0,.6,-1.1],[-1.1,.6,0]],'#ffffff','field');
if(park.id==='petco'){box(-95,83,25,28,22,'#a77867','Western Metal building');for(let floor=0;floor<3;floor++)for(let column=0;column<5;column++){const x=-92+column*4.6,y=4+floor*5.2;face([[x,y,82.9],[x+2,y,82.9],[x+2,y+2.8,82.9],[x,y+2.8,82.9]],'#435d5e','detail')}box(53,119,38,4,31,'#55727c','Outfield scoreboard')}
if(park.id==='dodger'){for(const x of [-75,28]){box(x,101,47,20,10,'#a6b6c2','Outfield pavilion');for(let strip=0;strip<12;strip++){const a=x+47*strip/12,b=x+47*(strip+1)/12,ha=19+1.3*Math.cos(strip*Math.PI/3),hb=19+1.3*Math.cos((strip+1)*Math.PI/3);panel([[a,ha,99],[b,hb,99],[b,hb+2,124],[a,ha+2,124]],'#e5ede9','Pavilion roof','roof')}box(x+6,125,32,3,24,'#55727c','Pavilion scoreboard')}}
if(park.id==='oracle'){const a=outfield[3],b=outfield[4];panel([a,b,[b[0],7.3,b[2]],[a[0],7.3,a[2]]],'#ad7962','Right-field wall');box(-58,123,36,3,27,'#55727c','Outfield scoreboard')}
sections.sort((a,b)=>a.id-b.id);
}
buildPark();
const lookup=id=>sections.find(s=>s.id===Number(id));
function seatPoint(s,row,seat){return polar(s.r0+(row-.5)*s.depth/20,s.start+(s.end-s.start)*(seat-.5)/20,s.height+row*s.depth/20*.47+1.1)}
function blocked(p,dir){for(const b of blockers){const h=cross(dir,b.e2),a=dot(b.e1,h);if(Math.abs(a)<1e-8)continue;const f=1/a,s=sub(p,b.p),u=f*dot(s,h);if(u<0||u>1)continue;const q=cross(s,b.e1),v=f*dot(dir,q);if(v<0||u+v>1)continue;const t=f*dot(b.e2,q);if(t>.05)return b.name}return null}
function status(s,row,seat,sol=sun){if(sol.alt<=0)return 'Sun below horizon';return blocked(seatPoint(s,row,seat),sol.dir)}
function project(p){const q=sub(p,focusPoint),x=q[0]*Math.cos(yaw)-q[2]*Math.sin(yaw),z=q[0]*Math.sin(yaw)+q[2]*Math.cos(yaw),y=q[1];const yy=y*Math.cos(pitch)+z*Math.sin(pitch),zz=y*Math.sin(pitch)-z*Math.cos(pitch);const scale=Math.min(W/290,H/220)*zoom;return[W/2+x*scale,H*.53-yy*scale,zz]}
function path(points){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath()}
function drawPoly(points,color,stroke){path(points);ctx.fillStyle=color;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.5;ctx.stroke()}}
function line(points,color,width=1){ctx.beginPath();points.map(project).forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()}
function darken(hex,amount=.63){const rgb=hex.match(/[a-f0-9]{2}/gi).map(v=>Math.round(parseInt(v,16)*amount));return `rgb(${rgb.join(',')})`}
function cameraPreset(which){mode=which;const s=lookup(selection);let target={yaw:0,pitch:.95,zoom:1,focus:[0,8,40]};if(which==='top')target={yaw:0,pitch:Math.PI/2,zoom:1,focus:[0,0,40]};if(which==='focus')target={yaw:Math.PI-(s.start+s.end)/2,pitch:1.05,zoom:1.75,focus:seatPoint(s,10,10)};let dy=target.yaw-yaw;while(dy>Math.PI)dy-=2*Math.PI;while(dy<-Math.PI)dy+=2*Math.PI;target.yaw=yaw+dy;cameraTween={start:performance.now(),from:{yaw,pitch,zoom,focus:[...focusPoint]},to:target};for(const [id,m] of [['reset','home'],['top','top'],['focus','focus']])$(id).setAttribute('aria-pressed',String(which===m));dirty=true}
function manualCamera(){cameraTween=null;mode='free';for(const id of ['reset','top','focus'])$(id).setAttribute('aria-pressed','false')}
function hitSection(x,y){for(const f of [...hitPolys].reverse()){let inside=false;for(let i=0,j=f.screen.length-1;i<f.screen.length;j=i++){const a=f.screen[i],b=f.screen[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside}if(inside)return f.id??null}return null}
function groundShadow(boundary){if(sun.alt<=0){drawPoly(boundary,'#21394a66');return}if(sun.dir[1]<.01)return;ctx.save();path(boundary);ctx.clip();ctx.beginPath();for(const b of blockers){const tri=[b.p,add(b.p,b.e1),add(b.p,b.e2)].map(p=>project([p[0]-p[1]*sun.dir[0]/sun.dir[1],.3,p[2]-p[1]*sun.dir[2]/sun.dir[1]]));if((tri[1][0]-tri[0][0])*(tri[2][1]-tri[0][1])-(tri[1][1]-tri[0][1])*(tri[2][0]-tri[0][0])<0)tri.reverse();ctx.moveTo(tri[0][0],tri[0][1]);ctx.lineTo(tri[1][0],tri[1][1]);ctx.lineTo(tri[2][0],tri[2][1]);ctx.closePath();/* Use consistent winding so overlapping triangles union. */}ctx.fillStyle='#18334855';ctx.fill();ctx.restore()}
function render(){ctx.clearRect(0,0,W,H);hitPolys=[];const bg=ctx.createRadialGradient(W/2,H/2,20,W/2,H/2,W*.7);bg.addColorStop(0,'#f6faf7');bg.addColorStop(1,'#dce9ed');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
const base=[[-132,-2,-85],[132,-2,-85],[132,-2,146],[-132,-2,146]].map(project);ctx.save();ctx.shadowColor='#42616b28';ctx.shadowBlur=25;ctx.shadowOffsetY=14;drawPoly(base,'#d8e1d9');ctx.restore();
if(park.id==='oracle'){const water=[[80,-1,48],[136,-1,48],[136,-1,144],[80,-1,144]];drawPoly(water.map(project),'#8cbfc9');for(let z=58;z<145;z+=12)line([[84,-.8,z],[135,-.8,z]],'#b7d9de',1)}
const fields=faces.filter(f=>f.kind==='field');drawPoly(fields[0].points.map(project),fields[0].color);ctx.save();path(fields[0].points.map(project));ctx.clip();for(let z=0;z<140;z+=12)drawPoly([[-100,.15,z],[100,.15,z],[100,.15,z+6],[-100,.15,z+6]].map(project),'#ffffff12');ctx.restore();for(const f of fields.slice(1))drawPoly(f.points.map(project),f.color);
line([fields[0].points[1],[0,.65,0],fields[0].points.at(-1)],'#fcfae6',1.8);line([[0,.65,0],[19.4,.65,19.4],[0,.65,38.8],[-19.4,.65,19.4],[0,.65,0]],'#eadbc5',1);
const mound=Array.from({length:32},(_,i)=>[2.7*Math.cos(i/32*Math.PI*2),.6,18.4+2.7*Math.sin(i/32*Math.PI*2)]);drawPoly(mound.map(project),'#cca682');line([[-.6,.7,18.4],[.6,.7,18.4]],'#fff',1.5);
groundShadow(fields[0].points.map(project));
const sorted=faces.filter(f=>f.kind!=='field'&&(f.kind!=='roof'||$('roofs').checked)).map(f=>({...f,screen:f.points.map(project)})).sort((a,b)=>a.screen.reduce((s,p)=>s+p[2],0)/a.screen.length-b.screen.reduce((s,p)=>s+p[2],0)/b.screen.length);
const overlay=$('overlay').checked;
for(const f of sorted){let color=f.color;if(f.kind==='seats'){const natural=palettes[park.id][lookup(f.sec).tier];color=overlay?(f.shade?'#547ea8':'#e5b852'):(f.shade?darken(natural):natural)}if(f.kind==='concourse'&&f.shade)color=darken(color,.7);drawPoly(f.screen,color,f.kind==='row'?'#a1b2aa':null);if(f.sec&&(f.sec===selection||f.sec===hovered)&&f.kind==='seats'){ctx.fillStyle=f.sec===hovered?'#ffffff33':'#ffffff16';ctx.fill()}hitPolys.push({screen:f.screen,id:f.sec});}
// A few recognition details, attached to the modeled structures.
if(park.id==='petco'){const anchor=project([-82,22.5,96]);ctx.font='bold 10px "DM Sans",sans-serif';ctx.textAlign='center';ctx.fillStyle='#fff4de';ctx.fillText('WESTERN METAL',anchor[0],anchor[1]);}
const occupied=[];for(const s of [...labels].sort((a,b)=>(b.id===selection?2:b.id===hovered?1:0)-(a.id===selection?2:a.id===hovered?1:0))){const prominent=s.id===selection||s.id===hovered;if(!prominent&&(zoom<1.3?(s.tier!==0||s.index%3!==0):zoom<1.8?s.index%2!==0:false))continue;const p=project(s.position);if(p[0]<25||p[0]>W-25||p[1]<65||p[1]>H-40)continue;if(!prominent&&occupied.some(q=>Math.abs(p[0]-q[0])<42&&Math.abs(p[1]-q[1])<23))continue;occupied.push(p);ctx.font=`${prominent?'bold ':''}12px "DM Sans",sans-serif`;ctx.textAlign='center';drawPoly([[p[0]-17,p[1]-12],[p[0]+17,p[1]-12],[p[0]+17,p[1]+8],[p[0]-17,p[1]+8]],prominent?'#244957':'#ffffffed');ctx.fillStyle=prominent?'#fff':'#375449';ctx.fillText(s.id,p[0],p[1]+2)}
const selected=seatPoint(lookup(selection),+$('row').value,+$('seat').value),p=project(selected);ctx.beginPath();ctx.arc(p[0],p[1],6,0,7);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#163b50';ctx.lineWidth=2;ctx.stroke();
for(const [text,pos] of [['HOME',[0,1,-6]],['1B',[26,1,23]],['3B',[-26,1,23]],['CENTER FIELD',[0,1,105]]]){const p=project(pos);ctx.font='bold 11px "DM Sans",sans-serif';ctx.textAlign='center';ctx.fillStyle='#f7fae9';ctx.fillText(text,p[0],p[1])}
const bearing=park.bearing*Math.PI/180,n=project([-100*Math.sin(bearing),0,100*Math.cos(bearing)]),o=project([0,0,0]);$('compass').style.transform=`rotate(${Math.atan2(n[0]-o[0],o[1]-n[1])*180/Math.PI}deg)`;
if(sun.alt>0){const origin=project([0,0,40]),s=project([sun.dir[0]*120,0,40+sun.dir[2]*120]),dx=s[0]-origin[0],dy=s[1]-origin[1],length=Math.hypot(dx,dy)||1,r=Math.min(W*.34,H*.37),sx=W/2+dx/length*r,sy=Math.max(88,Math.min(H-55,H*.5+dy/length*r));ctx.save();ctx.setLineDash([3,5]);ctx.strokeStyle='#bf983c70';ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(W/2+(sx-W/2)*.72,H*.5+(sy-H*.5)*.72);ctx.stroke();ctx.setLineDash([]);ctx.shadowColor='#f0bf51';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(sx,sy,11,0,7);ctx.fillStyle='#f4c760';ctx.fill();ctx.shadowBlur=0;for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.beginPath();ctx.moveTo(sx+15*Math.cos(a),sy+15*Math.sin(a));ctx.lineTo(sx+19*Math.cos(a),sy+19*Math.sin(a));ctx.strokeStyle='#b98d2f';ctx.stroke()}ctx.font='12px "DM Sans"';ctx.textAlign='center';ctx.fillStyle='#705923';ctx.fillText('SUN',sx,sy+33);ctx.restore()}
$('sun-legend').style.display=overlay?'flex':'none';dirty=false}
function formatTime(m){const h=Math.floor(m/60);return`${h%12||12}:${String(m%60).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function calculate(){sun=solar(date,minute);for(const f of faces)if(f.kind==='seats')f.shade=status(lookup(f.sec),f.sample.row,f.sample.seat);else if(f.samplePoint)f.shade=sun.alt<=0||blocked(f.samplePoint,sun.dir);$('clock').innerHTML=formatTime(minute).replace(/ (AM|PM)/,' <span>$1</span>');$('altitude').textContent=sun.alt>0?`☀ Sun elevation ${sun.alt.toFixed(1)}°`:'☾ Sun below horizon';$('azimuth').textContent=`Bearing ${Math.round(sun.az)}° from north`;updateSeat(false);dirty=true}
function updateSeat(timeline=true){selection=+$('section').value;const s=lookup(selection),row=+$('row').value,seat=+$('seat').value,b=status(s,row,seat);$('result').textContent=b?(sun.alt<=0?'Sun below horizon':'In modeled shade'):'In modeled sunlight';$('result-icon').textContent=b?'◐':'☀';$('seat-label').textContent=`Section ${s.id} · Row ${row}, seat ${seat}*`;$('reason').textContent=b?b==='Sun below horizon'?'No direct sunlight at this time.':`Blocked by ${b.toLowerCase()}.`:'Direct sun in the current model.';document.querySelector('.result').style.background=b?'#e7eef6':'#fff1cb';if(timeline){$('dayline').replaceChildren();for(let m=600;m<=1200;m+=20){const b=status(s,row,seat,solar(date,m)),btn=document.createElement('button');btn.style.background=b?'#547ea8':'#e5b852';btn.title=`${formatTime(m)}: ${b?'shade':'sun'}`;btn.setAttribute('aria-label',btn.title);btn.onclick=()=>{userChoice();setTime(m)};$('dayline').append(btn)}}dirty=true}
function setTime(m){minute=m;$('time').value=m;calculate()}
let choiceRevision=0;
function userChoice(){choiceRevision++}
function setDate(d){if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d))||d<'2026-01-01'||d>'2026-12-31')return;date=d;calculate();updateSeat()}
sections.sort((a,b)=>a.id-b.id).forEach(s=>$('section').add(new Option(`${s.id}`,s.id)));$('section').value=selection;for(let i=1;i<=20;i++){$('row').add(new Option(i,i));$('seat').add(new Option(i,i))}$('row').value=15;$('seat').value=10;
$('time').oninput=e=>{userChoice();setTime(+e.target.value)};for(const id of ['section','row','seat'])$(id).onchange=()=>{updateSeat();if(mode==='focus')cameraPreset('focus')};$('roofs').onchange=$('overlay').onchange=()=>dirty=true;$('reset').onclick=()=>cameraPreset('home');$('top').onclick=()=>cameraPreset('top');$('focus').onclick=()=>cameraPreset('focus');$('about').onclick=$('seat-about').onclick=()=>$('method').showModal();$('close').onclick=()=>$('method').close();$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',playing?'Pause time':'Animate time')};
let drag=null;canvas.onpointerdown=e=>{cameraTween=null;drag={x:e.clientX,y:e.clientY,initialX:e.clientX,initialY:e.clientY};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect();if(drag){manualCamera();yaw+=(e.clientX-drag.x)*.008;pitch=Math.max(.25,Math.min(Math.PI/2,pitch-(e.clientY-drag.y)*.006));drag.x=e.clientX;drag.y=e.clientY;dirty=true;$('hover-label').hidden=true}else{const x=e.clientX-r.left,y=e.clientY-r.top,next=hitSection(x,y);if(next!==hovered){hovered=next;dirty=true}const label=$('hover-label');label.hidden=!next;if(next){label.textContent=`${lookup(next).name} · Section ${next}`;label.style.left=`${Math.max(8,Math.min(W-170,x+15))}px`;label.style.top=`${Math.max(65,y-32)}px`}canvas.style.cursor=next?'pointer':'grab'}};canvas.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag.initialX,e.clientY-drag.initialY)<5){const r=canvas.getBoundingClientRect(),id=hitSection(e.clientX-r.left,e.clientY-r.top);if(id){$('section').value=id;updateSeat();if(mode==='focus')cameraPreset('focus')}}drag=null};canvas.onpointercancel=()=>drag=null;canvas.onpointerleave=()=>{hovered=null;$('hover-label').hidden=true;dirty=true};canvas.addEventListener('wheel',e=>{e.preventDefault();manualCamera();zoom=Math.max(.6,Math.min(2.5,zoom*Math.exp(-e.deltaY*.001)));dirty=true},{passive:false});
new ResizeObserver(()=>{const r=canvas.getBoundingClientRect();W=r.width;H=r.height;const dpr=Math.min(devicePixelRatio,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);dirty=true}).observe(canvas);
let scheduleVersion=0,scheduledGames=[];
function syncParkUI(){
$('ballpark').value=park.id;$('park-name').textContent=park.name;$('park-location').textContent=`${park.city}, ${park.state} · ${park.team}`;$('local-time-label').textContent=`${park.city.toUpperCase()} TIME`;
$('model-notes').textContent=park.notes;$('model-bearing').textContent=`${park.bearing}°`;$('venue-source').href=`https://statsapi.mlb.com/api/v1/venues/${park.venueId}?hydrate=location,fieldInfo`;
$('schedule-source').href=`https://statsapi.mlb.com/api/v1/schedule?sportId=1&teamId=${park.teamId}`;
$('section').replaceChildren(...sections.map(s=>new Option(`${s.id} · ${s.name}`,s.id)));selection=sections.find(s=>s.id===102)?.id??sections[0].id;$('section').value=selection;
}
function applyGame(g){const local=gameLocal(g,park);setDate(local.date);setTime(Math.max(360,Math.min(1320,local.timeKnown?local.minutes:790)));$('games').value=String(g.gamePk);$('schedule-note').textContent=local.timeKnown?'MLB game time · Times may change.':'Game time TBD · Showing 1:10 PM for exploration.'}
async function loadGames(upcoming=false){
const version=++scheduleVersion,revision=choiceRevision,selectedPark=park,now=Date.now(),start='2026-01-01',end='2026-12-31';
$('games').disabled=true;$('games').replaceChildren(new Option('Loading home games…',''));$('schedule-note').textContent=upcoming?'Finding the next home game…':'Loading MLB schedule…';
try{const response=await fetch(`https://statsapi.mlb.com/api/v1/schedule?sportId=1&teamId=${selectedPark.teamId}&season=2026&gameTypes=R,F,D,L,W&startDate=${start}&endDate=${end}`,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Schedule request failed');const data=await response.json();if(version!==scheduleVersion||park.id!==selectedPark.id)return;
scheduledGames=homeGames(data,selectedPark);$('games').replaceChildren(new Option('Choose a home game…',''));
for(const g of scheduledGames){const local=gameLocal(g,park);$('games').add(new Option(`${local.date} · ${g.teams.away.team.name} · ${local.timeKnown?formatTime(local.minutes):'Time TBD'}`,g.gamePk))}
$('games').disabled=!scheduledGames.length;const next=upcoming?nextHomeGame(scheduledGames,now):null,recent=upcoming&&!next?scheduledGames.filter(g=>Date.parse(g.gameDate)<=now).at(-1):null,initial=next??recent;
if(initial&&revision===choiceRevision){applyGame(initial);$('schedule-note').textContent=next?(gameLocal(next,park).timeKnown?'Next home game · MLB time; subject to change.':'Next home game · Start time TBD.'):'Most recent 2026 home game.'}
else $('schedule-note').textContent=scheduledGames.length?'2026 season · Past and upcoming home games.':'No 2026 home games found.';
}catch{if(version!==scheduleVersion)return;scheduledGames=[];$('games').replaceChildren(new Option('Schedule unavailable',''));$('schedule-note').textContent='MLB schedule unavailable. Try again later.'}
}
$('games').onchange=e=>{const game=scheduledGames.find(g=>String(g.gamePk)===e.target.value);if(game){choiceRevision++;applyGame(game)}};
$('ballpark').replaceChildren(...parks.map(p=>new Option(`${p.name} · ${p.team}`,p.id)));
$('ballpark').onchange=e=>{const next=parks.find(p=>p.id===e.target.value);if(!next||next===park)return;choiceRevision++;park=next;playing=false;$('play').textContent='▶';$('play').setAttribute('aria-label','Animate time');date=seasonDate();minute=790;$('time').value=minute;buildPark();syncParkUI();hovered=null;cameraPreset('home');calculate();updateSeat();loadGames(true)};
syncParkUI();calculate();updateSeat();loadGames(true);
function loop(t){if(cameraTween){const c=cameraTween,u=Math.min(1,Math.max(0,(t-c.start)/550)),e=1-Math.pow(1-u,3);yaw=c.from.yaw+(c.to.yaw-c.from.yaw)*e;pitch=c.from.pitch+(c.to.pitch-c.from.pitch)*e;zoom=c.from.zoom+(c.to.zoom-c.from.zoom)*e;focusPoint=c.from.focus.map((v,i)=>v+(c.to.focus[i]-v)*e);dirty=true;if(u===1)cameraTween=null}if(playing&&t-last>350){setTime(minute>=1320?360:minute+5);last=t}if(dirty&&W)render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_shade_simulation',description:'Set the visible date, the selected ballpark’s local time and illustrative model seat; return estimated sun or shade.',inputSchema:{type:'object',properties:{date:{type:'string'},minutes:{type:'integer',minimum:360,maximum:1320},section:{type:'integer'},row:{type:'integer',minimum:1,maximum:20},seat:{type:'integer',minimum:1,maximum:20}},required:['date','minutes','section','row','seat'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!/^\d{4}-\d{2}-\d{2}$/.test(input.date)||!Number.isFinite(Date.parse(input.date))||input.date<'2026-01-01'||input.date>'2026-12-31'||!lookup(input.section)||![input.row,input.seat].every(v=>Number.isInteger(v)&&v>=1&&v<=20)||!Number.isInteger(input.minutes)||input.minutes<360||input.minutes>1320)throw Error('Invalid date, time or model seat');userChoice();$('section').value=input.section;$('row').value=input.row;$('seat').value=input.seat;setDate(input.date);setTime(input.minutes);updateSeat();return{park:park.id,date,time:formatTime(minute),section:selection,row:input.row,seat:input.seat,result:$('result').textContent,provisionalGeometry:true}}})).catch(()=>{})}catch{}}
